### ISSUE TITLE
Last versions not available on PPA ?

### ISSUE THREAD

**Issue by mikaelarguedas** [fkie/catkin_lint#114]
Hey there thanks for this project !

I'm on Ubuntu 24.04 and would love to benefit from the fixes of the recent versions.

I can install it from pip but would like to be able to install it from APT.

Would it be possible to have them available on the PPA ?

Thanks!

PS: this is also a requirementn to get an updated version of the package to be imported in the ROS apr repository

**Comment by roehling** [comment]
I've updated the PPA for Ubuntu 20.04 and added a build for Ubuntu 22.04. However, Canonical has removed most of the ROS related packages from the Ubuntu 24.04 release, and as I cannot add non-PPA package sources to a PPA, I cannot build catkin_lint in Ubuntu any more. Debian still works, though ;)
