### ISSUE TITLE
Getting "list COMPONENTS should be sorted" even though they already appear to be

### ISSUE THREAD

**Issue by gavanderhoorn** [fkie/catkin_lint#21]
Running `catkin_lint -W2 /path/to/my/pkgs` results in:
```
my_pkg: CMakeLists.txt(4): notice: list COMPONENTS should be sorted
```

for the following snippet:
```cmake
find_package(catkin REQUIRED COMPONENTS
  moveit_core
  pluginlib
  roscpp
  tf_conversions
)
```

As far as I can tell the `COMPONENTS` arguments are actually sorted alphabetically (and SublimeText seems to agree).

**Comment by gavanderhoorn** [comment]
Thanks.

**Comment by roehling** [comment]
No, thank you! Your testing and bug reports make catkin_lint a better tool, and I appreciate that very much.
