### ISSUE TITLE
Kinetic version of catkin_lint?

### ISSUE THREAD

**Issue by jack-oquin** [fkie/catkin_lint#29]
I recently installed Xenial and ROS Kinetic, but ``sudo apt-get install python-catkin-lint`` does not work.

There are other ways to install it, but I wonder if there is a plan to release it to the Kinetic repositories?

**Comment by roehling** [comment]
Hm, there is a Xenial version in my Launchpad PPA. Maybe @tfoote can help?

**Comment by jack-oquin** [comment]
Your PPA is fine for now. I didn't think of looking there.

I guess the advantage of adding it to the ROS repository is for packages to list it as a dependency.

**Comment by tfoote** [comment]
I imported the new ppa build into the ROS repos. The packages will be available shortly.

**Comment by roehling** [comment]
Thanks, @tfoote.

I think you can remove quantal, raring, and saucy from the list since they reached EOL and have been removed from the PPA. Furthermore, I started packaging a Python 3 version which you may want to import as well (`python3-catkin-lint`).

**Comment by tfoote** [comment]
Imported, and they'll propogate with the next syncs
