### ISSUE TITLE
Suggestion: Warn on Uninstalled Executables

### ISSUE THREAD

**Issue by evenator** [fkie/catkin_lint#31]
A common mistake is to forget to install an executable script (bash, python, etc) with CMake. The script will `rosrun` fine from the devel space, but won't be present in the install build. As far as I can tell, catkin_lint doesn't currently check for this. Would others be interested in this feature? If so, I might work on a PR.

**Comment by roehling** [comment]
Good idea. You want to try to implement it yourself or leave it to me?

**Comment by evenator** [comment]
Hey, I just got a chance to check on this. Thanks for the feature!
