### ISSUE TITLE
<depend> declaration tag handling 

### ISSUE THREAD

**Issue by dseifert** [fkie/catkin_lint#34]
In #32 / v1.4.10 a check for sorted build_depend, exec_depend, etc values was introduced. However it does not handle use of the `<depend>` tag well, which is a shortcut for specifying `build_depend`, `build_export_depend` and `exec_depend` for the same package (http://www.ros.org/reps/rep-0140.html#depend-multiple). Apparent from making it easier to read corresponding package.xml files as they become shorter, it is also less prone to forgetting one of the tags.

However, as this tag is (apparently) resolved to build_depend, build_export_depend and exec_depend at loading, the following valid package.xml causes issues with the declaration tag sort check:
```
<build_depend>only_for_compilation</build_depend>

<depend>a_pkg</depend>
<depend>yet_another_pkg</depend>
```
It is impossible to order these three lines to satisfy the check, unless the `<depend>` tags are written as their three underlying tags (i.e. adding another 4 lines).

Short of parsing package.xml in catkin_lint itself or declaring the use of `<depend>` unwanted, I don't know how to solve this issue.

**Comment by roehling** [comment]
Yes, I noticed that, too. I was still thinking of a way to fix this, but short of implementing my own package.xml parsing, nothing comes to mind. I'll probably end up removing this check again in the next version.
