### ISSUE TITLE
Autocorrect feature

### ISSUE THREAD

**Issue by nikste** [fkie/catkin_lint#35]
Would be nice to have an auto correct feature for stuff like:
`CMakeLists.txt(5): notice list COMPONENTS should be sorted`

**Comment by roehling** [comment]
It is a nice idea. I'm not sure if there are sufficiently many use cases besides sorting and indentation, though. Maybe this should be a stand-alone CMake formatter?

**Comment by koenlek** [comment]
There is a tool that already does that:
https://github.com/DLu/roscompile

I proposed integrating that tool with catkin lint in this issue: https://github.com/DLu/roscompile/issues/37
