### ISSUE TITLE
Catkin_lint error

### ISSUE THREAD

**Issue by mnksnz** [fkie/catkin_lint#44]
Running catkin_lint throws the following error:

catkin_lint: internal error: 'Package' object has no attribute 'version_abi'

Thanks in advance! :)

**Comment by roehling** [comment]
The Package object has changed internally, and the cached package lists are not properly deleted. As a workaround, run  `catkin_lint --clear-cache` once.

**Comment by mnksnz** [comment]
Works! Thanks.
