### ISSUE TITLE
Configured files are not handled

### ISSUE THREAD

**Issue by VictorLamoine** [fkie/catkin_lint#54]
- Configure a file in the CMake: https://gitlab.com/InstitutMaupertuis/ros_additive_manufacturing/blob/melodic/ram_qt_guis/CMakeLists.txt#L421-426
- Install the (configured) file: https://gitlab.com/InstitutMaupertuis/ros_additive_manufacturing/blob/melodic/ram_qt_guis/CMakeLists.txt#L428-434

catkin_lint complains about installing a file that does not exist:
```
ram_qt_guis: CMakeLists.txt(429): error: install() needs missing file '/pkg-build/script/ros_additive_manufacturing.bash'
```

https://gitlab.com/InstitutMaupertuis/ros_additive_manufacturing/-/jobs/85248787

---

The file will be created on configuration and it will exist, `catkin_lint` does not "understand" that.

**Comment by roehling** [comment]
Yes, `catkin_lint` does not handle `configure_file()` nor `add_custom_command()` yet. For now, I decided to handle this corner case by ignoring missing files if they are not in the package source tree, the same way it is handled for other source files.

The proper solution will follow when I find time to do it.
