### ISSUE TITLE
catkin_lint reports not sorted NOINSTALL as error

### ISSUE THREAD

**Issue by JKBehrens** [fkie/catkin_lint#59]
catkin_lint reports an error for the following snippet of a CMakeLists.txt, but NOINSTALL is required to be at the end (http://docs.ros.org/kinetic/api/genmsg/html/usermacros.html).
```
add_message_files(
  FILES
  A.msg
  Z.msg
  NOINSTALL
)
```

**Comment by roehling** [comment]
Thanks for the report! I didn't notice the additional macro parameters which were added to the add_message_files() call some time ago.
