### ISSUE TITLE
allow variable names in cmake version checks

### ISSUE THREAD

**Issue by rhaschke** [fkie/catkin_lint#61]
catkin_lint suggests to change
`if(rviz_QT_VERSION VERSION_LESS "5")`
into
`if("${rviz_QT_VERSION}" VERSION_LESS "5")`

with the following `notice: operands for operator VERSION_LESS should be quoted strings`.

However, using a variable name directly, without quoting and resolving is perfectly valid and IMHO much more readable. Could you improve this check, please?

**Comment by roehling** [comment]
I improved the check, because the main goal was to prevent constructs like

    set(var1 OFF)
    set(var2 var1)
    # ...
    if(${var2})
        # ...
    endif()

In this case, `${var2}` resolves to `var1`, and `var1` is then treated as variable and resolved *again*.

**Comment by rhaschke** [comment]
Isn't that something we would like to happen?

**Comment by roehling** [comment]
If you are very adept with CMake, maybe. Most people I know are surprised by this behavior, which is exactly why `catkin_lint` warns about it in the first place.
