### ISSUE TITLE
cmake INTERFACE libraries

### ISSUE THREAD

**Issue by tylerjw** [fkie/catkin_lint#72]
`add_library(code_coverage_config INTERFACE)`

Will generate the error:

`add_library() needs missing file 'INTERFACE'`

This is valid cmake and INTERFACE is not a file but a part of the api for adding interface libraries.

Secondly, interface libraries can be used to add compile/link options and then they can be added to targets.  These libraries have no files and do not to be installed.  However they will generate these errors if they aren't `installed`:

`target 'example' depends on target 'code_coverage_config' which is not installed`

**Comment by roehling** [comment]
I haven't yet implemented support for interface libraries. Thanks for the bugreport, I'll see to it.
