### ISSUE TITLE
Skip packages by path

### ISSUE THREAD

**Issue by khssnv** [fkie/catkin_lint#75]
Hello. I see there is an option to skip a check for a certain package with `--skip-pkg` by package name. Is it possible to skip by packages path? My use case: there are externals (packages and meta-packages) my packages depends on. I want to skip checks for externals, but leave them in environment to keep my packages dependencies reachable.

**Comment by roehling** [comment]
If your own packages and your external dependencies are in different subtrees, you can just do `catkin_lint /path/to/my/packages`.

`catkin_lint` will use the package paths taken from the `ROS_PACKAGE_PATH` environment variable and the `--package-path` option to resolve dependencies, but not actively check them. If you run `catkin_lint /foo --package-path /bar`, then all packages in `/foo` will be checked, but packages in `/bar` will only be used to resolve dependencies.

There is no option yet to exclude a subfolder from a path that is checked.
