### ISSUE TITLE
catkin_lint fails to run because of XML declaration

### ISSUE THREAD

**Issue by mvieth** [fkie/catkin_lint#81]
Message: `catkin_lint: cannot lint my_package: Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.`

The problem seems to happen because a launch file contains an XML declaration like this: `<?xml version="1.0" encoding="UTF-8"?>`. If the declaration is removed, catkin_lint works fine.

I installed catkin_lint with pip. Version is 1.6.8.

**Comment by mvieth** [comment]
Wow, that was fast!

**Comment by roehling** [comment]
Thank you, that's because you gave an excellent bug report with the exact error message, and you even found the minimum required change to trigger the bug.
