### ISSUE TITLE
APPEND_COVERAGE_COMPILER_FLAGS() should be all lower-case

### ISSUE THREAD

**Issue by Timple** [fkie/catkin_lint#88]
I simply took it from this manual: https://github.com/mikeferguson/code_coverage

And since I cannot influence this function name, would it make sense to ignore it?

**Comment by roehling** [comment]
CMake Macro names and function names are case-insensitive, so you can make the call lower-case. Alternatively, you could prepend the call site with a line that reads `#catkin_lint: ignore_once cmd_case`

**Comment by Timple** [comment]
Aah, didn't know they where case-insensitive. Never mind then :)
