### ISSUE TITLE
include directory check

### ISSUE THREAD

**Issue by asherikov** [fkie/catkin_lint#92]
Hi, nice tool, thanks.

I wonder if it is possible to add a warning if headers installed to CATKIN_PACKAGE_INCLUDE_DESTINATION don't match
'include/<package_name>/*' pattern as in http://wiki.ros.org/catkin/CMakeLists.txt#Installing_header_files.

Also, personally I would prefer to get relative paths to offending files instead of '<package_name>: package.xml ...', it would save me a couple of seconds when fixing an issue ;).

**Comment by roehling** [comment]
I added a check for the `CATKIN_PACKAGE_INCLUDE_DESTINATION`.

As for the paths, they are relative to the package directory already. All you need to do is run `roscd $PACKAGE` first. Revamping my output code (that supports different output formats) would be more work than you'll ever save, so I'll have to decline that request.

**Comment by asherikov** [comment]
thanks for a quick response
